name: cln_plugin
description: Template to write a plugin for core lightning in dart lang.
version: 1.0.0
homepage: https://github.com/dart-lightning/kraken

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cln_plugin_api: ^0.0.1-beta.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
